### ISSUE TITLE
IPv6 Support

### ISSUE THREAD

**Issue by anthonysomerset** [karelia/CurlHandle#14]
I remember the old (ancient) versions had zero support for IPv6, is this still the case in current versions, i cant find any release notes that suggest it is now supported

if not consider this is a feature request :)

**Comment by mikeabdullah** [comment]
As far as I'm aware IPv6 requests work just fine. We're simply handing off URL strings to libcurl; not doing any address-specific handling that I recall. Try it, and let me know if there's a problem :)

**Comment by anthonysomerset** [comment]
confirmed works fine!
