### ISSUE TITLE
Repository should contain CurlHandle's MacPorts portfile and keep it up to date

### ISSUE THREAD

**Issue by cooljeanius** [karelia/CurlHandle#4]
MacPorts is considering updating the CurlHandle port to use this repository (see http://trac.macports.org/ticket/13890#comment:8 for more info), however, it'd be easier if you guys would just keep the portfile up to date yourselves...

**Comment by ryandesign** [comment]
The MacPorts project is of course happy to receive updates to portfiles. But there's no particular reason why the portfile for curlhandle or any other port should need to live anywhere other than the MacPorts repository.

**Comment by ryandesign** [comment]
I've updated the MacPorts curlhandle port to 3.1.1. It seems to compile fine.

**Comment by cooljeanius** [comment]
OK never mind
