### ISSUE TITLE
SFTP usage

### ISSUE THREAD

**Issue by dbainbridge** [karelia/CurlHandle#7]
Am I to understand that if you need to support both FTP and SFTP you need to also use the CK2SFTPSession class from https://github.com/karelia/libssh2_sftp-Cocoa-wrapper? or should we be using the latest ConnectionKit to get both?

**Comment by mikeabdullah** [comment]
Hi,

For SFTP support, you're almost certainly best off going through ConnectionKit 2 than CURLHandle. There's quite a bit of extra management required of CURLHandle that's a waste of your time to have to write.
